version: '3.0'

services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crud
  
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    depends_on: 
      - db
